### ISSUE TITLE
how to compute by points label?

### ISSUE THREAD

**Issue by hiphapis** [appneta/burndown#65]
Now burndown does just compute open/close issues.
i want to compute by `points-\d+` label.
![image](https://cloud.githubusercontent.com/assets/18629/6802032/3836da9c-d270-11e4-91a3-1eccd46cdaac.png)

could you have plan for this feature?
if you does not have plan, please let me know how to do it

**Comment by danriti** [comment]
hey @hiphapis, this was requested and implemented in a previous issue:

https://github.com/appneta/burndown/pull/48#issuecomment-39866449

You can simply add a `Weight: N` label to any of your issues, where `N` is the size/weight/points that you want to assign to the issue.

**Comment by hiphapis** [comment]
@danriti wow!! great!! Thank you!
