### ISSUE TITLE
Support Github Organization Third Party Access

### ISSUE THREAD

**Issue by dankohn** [appneta/burndown#68]
I turned on the "Third-party application access policy" for my Github Organization. I can no longer access burndown.io for our private repo. Could you please update your sign-in process for private repos to support third party application restrictions (you just need to register your application with Github and update the sign-in process).

https://help.github.com/articles/about-third-party-application-restrictions/

Thanks! I love burndown and will be sorry to miss it. Note that CircleCI and Waffle both worked with the third party access.

**Comment by dankohn** [comment]
Sorry, it works fine. I just needed to revoke access from https://github.com/settings/applications and then grant it back again.

**Comment by danriti** [comment]
No worries @dankohn!
